### ISSUE TITLE
RFC Removal of default permissions

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-records#137]
### Proposal

Can we remove `invenio_records.permissions` module as it is not recommended for large repositories to store per record access rights in `invenio-access`?

--
cc @inveniosoftware/triagers

**Comment by tiborsimko** [comment]
Indeed, we may want to recommend to use the collection concept instead. Note that this is touching the forthcoming "Invenio 3 Beta Access" sprint on how the recommended access control may look like; hopefully uniformly across services. E.g. CDS started to experiment with an alternative approach to collections... https://github.com/CERNDocumentServer/cds/pull/160#issuecomment-229615330

**Comment by nharraud** [comment]
@jirikuncar I understand the need to remove the permission per record as it would bloat the database. However having a permission for reading, updating, deleting, creating ALL records can be useful. That way it is possible to create custom admin roles.

@tiborsimko I would be interested to see the suggested designs for permissions. We started some time ago a specification document for the permissions in B2Share. I would like to see how well these designs match our needs.
The code I see in the mentioned PR looks like what we where doing for the CloudView search engine and it worked well for search filtering.

**Comment by nharraud** [comment]
Ok for removing the permissions from invenio-records. As there are different kind of records (ex: deposits), having generic records permissions does not make sense anymore.

**Comment by tiborsimko** [comment]
I'd be also in favour of decoupling `permissions` better... But let's see @lnielsen's original use case for including it here and @egabancho`s  RFC https://github.com/inveniosoftware/invenio-access/issues/70

**Comment by lnielsen** [comment]
I think we can remove it, but I would appreciate if you could test out #138 on Zenodo. Basically, install Zenodo with #138, and run the tests.

Just to ensure that there's no collateral damage from making this change.
