### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-records#140]
- [ ] check existing API functionality
  - [ ]  api: allow partial validation #146 
- [ ] add missing important API functionality
- [ ] check API function signatures and parameters
- [x] enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- [x] plug API functions to existing docs

**Comment by hachreak** [comment]
@jirikuncar @lnielsen do you think the first 3 points are fine? Or do we need to improve somehow the API?

**Comment by jirikuncar** [comment]
What about #137 (#138)? cc @tiborsimko @lnielsen

**Comment by hachreak** [comment]
#137 and #138 done!
