### ISSUE TITLE
api: make the FormatChecker feature of jsonschema accessible

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware/invenio-records#142]
The `jsonschema` library that we use for validation requires a `FormatChecker` class to be passed to the validator in order to validate the `format` keyword: https://github.com/Julian/jsonschema/blob/37a7bb96cacb7db6e589bdb054e49e62c4367a7e/jsonschema/_format.py#L13-L15.

Invenio-Records currently does not support this: https://github.com/inveniosoftware/invenio-records/blob/aab3b024d0078ccd36334e1d2faae02d078c8882/invenio_records/ext.py#L49-L57.

A quick fix would be to add `**kwargs` to https://github.com/inveniosoftware/invenio-records/blob/aab3b024d0078ccd36334e1d2faae02d078c8882/invenio_records/api.py#L78-L82 and the previous method, but I'm not sure if you'd like such a "liberal" solution.

**Comment by jirikuncar** [comment]
IMHO we can add `**kwargs` together with good example in docstring.
