### ISSUE TITLE
api: additional properties

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-records#166]
`invenio-deposit.api.Deposit` already has some convenient properties such as [`pid` and `record_schema`](https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L143-L158). These could be defined in the `invenio_records.api.Record` base class and maybe use some standard class members to work with (in the likes of [`deposit_fetcher`](https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L137)).

**Comment by lnielsen** [comment]
Main issue as I see is that Records have no dependency on PIDStore today and we've been trying hard to keep it that way.

**Comment by slint** [comment]
:+1: For keeping them separate. 

Maybe a mixin in PIDStore then (something in `invenio_pidstore.contrib.records`, or `invenio_pidstore.mixins`). So I guess this can be closed.
