### ISSUE TITLE
cli: "records delete" does not delete records marked as deleted

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-records#173]
**Scenario:**
- call `invenio records delete <ID>`
- call `invenio records delete --force <ID>`

=> this fails

**Problem:**
`invenio records delete` [calls `get_records` without setting `with_deleted=True`](https://github.com/inveniosoftware/invenio-records/blob/c4af2bd5b67ae6bb627d01cd97d58b0417baf810/invenio_records/cli.py#L166).

**Comment by egabancho** [comment]
Shouldn't `with_deleted` be connected with `--force` only?
