### ISSUE TITLE
alembic revision containing only numbers in hash

### ISSUE THREAD

**Issue by dinosk** [inveniosoftware/invenio-records#174]
The revision 862037093962_create_records_tables.py contains only numbers in its hash, and there is a [bug](https://bitbucket.org/davidism/flask-alembic/src/e036f063af1ba667c74560264639a93d812dfd51/flask_alembic/extension.py?at=default&fileviewer=file-view-default#extension.py-335) in Flask-Alembic, which results in an error when giving this revision as target:
`alembic.util.exc.CommandError: Relative revision -862037093962 didn't produce 862037093962 migrations`
It handles it as a relative migration identifier, like `alembic upgrade +2`
Changing the hash should fix this for now.
If there are instances which include this revision in their alembic version table it could be changed manually.

**Comment by dinosk** [comment]
The fix for this is included in @jmartinm 's PR https://github.com/inveniosoftware/invenio-records/compare/master...jmartinm:upgrade-to-jsonb

**Comment by lnielsen** [comment]
What is the impact of this? That you cannot run alembic stamp on that specific revision?

**Comment by dinosk** [comment]
Only impact is you cannot downgrade or upgrade specifically to this revision directly by `alembic downgrade 862037093962`, doing it step by step with `alembic downgrade -1` or `alembic upgrade +2` works ok.

**Comment by lnielsen** [comment]
Ok, then perhaps we should just leave it as is, since this recipe is already on production system by now
