### ISSUE TITLE
utils: remove legacy functions

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-records#18]

**Comment by hachreak** [comment]
The legacy code is used here:
- [ ] utils.py [references_nb_counts](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/utils.py#L107)
- [ ] test_record.py [test_legacy_create_recstruct()](https://github.com/inveniosoftware/invenio-records/blob/master/tests/test_record.py#L116), [test_legacy_export_marcxml()](https://github.com/inveniosoftware/invenio-records/blob/master/tests/test_record.py#L85)

**Comment by hachreak** [comment]
@jirikuncar can I remove the [references_nb_counts()](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/utils.py#L101) function?
