### ISSUE TITLE
Use record_class similarly to invenio_records_rest

### ISSUE THREAD

**Issue by carantunes** [inveniosoftware/invenio-records#216]
Removing records with admin leads to errors because Record class is not configurable. https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/admin.py#L54

Request: Make record_class configurable like in invenio-records-rest: https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/config.py

**Comment by lnielsen** [comment]
There's more problems as well. The record delete doesn't delete associated Persistent Identifiers, nor related files, so all in all the admin as it is now is quite useless.
