### ISSUE TITLE
dumpers: make `indexed_at` pop optional

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-records#280]
The `IndexedAtDumperExt` could optionally pop the `self.key` on loading. 

Note that this might generate the need to add it also "optional" in the marshmallow schema and jsonschema (which boils down somehow to a model field too? 🤔)

**Comment by lnielsen** [comment]
Is this needed near-term or any chance of implementing it anytime soon? If not, I would simply close the issue.

**Comment by ppanero** [comment]
It was just a potential improvement, but it is definitely not needed. Came out of [this comment](https://github.com/inveniosoftware/invenio-records/pull/279#discussion_r844021965).

 Closing... (cc @slint in case Im mistaken hehe)
