### ISSUE TITLE
signals: record enhancers

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio-records#48]
In order to enhance on the fly a record being sent to elasticsearch for indexing a receiver for the events `after_record_insert`, `after_record_update` needs to be created that would execute all the enhancers collected via a registry, passing the current record being sent and returning an enhanced record.

**Comment by jmartinm** [comment]
:+1:

**Comment by tiborsimko** [comment]
Note: needed for JSON enrichment from authority records  https://github.com/inveniosoftware/invenio-authorities/issues/1 and more tasks of this kind (e.g. special author name tokeniser).

**Comment by lnielsen** [comment]
This belongs to Invenio-Search now, and is perhaps not needed anymore. See https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/contrib/records.py#L40-L57

**Comment by kaplun** [comment]
@lnielsen the code you mention is not extensible. Instead each service would need to reimplement it from scratch and they would probably need to add a signal or something similar in order be able to plug little by little more enhancers.

Addditionally the signal in the mention code is fired upon every model being touched. Isn't this overkill?

A dedicated signal for indexing seems to me a more high-level and semantic approach.

**Comment by egabancho** [comment]
@kaplun this signal is, AFAIK, the only one that can tell you when the record was committed to the database, others like `after_insert` are triggered before the commit (when the nested transaction ends) instead which could result in having indexed records that are not finally committed for some reason

**Comment by kaplun** [comment]
Fair enough. Then what about if the signal mentioned in this is very issue is included in the referred code as in:

@models_committed.connect
def index_record_modification(sender, changes):
    """Example handler for indexing record metadata."""
    for obj, change in changes:
        if isinstance(obj, RecordMetadata):
            if change in ('insert', 'update'):
                before_record_index.send(obj.id, json=obj.json) # <-- here it is
                current_search_client.index(
                    index='records',
                    doc_type='record',
                    id=obj.id,
                    body=obj.json,
                )
            elif change in ('delete'):
                current_search_client.delete(
                    index='records',
                    doc_type='record',
                    id=obj.id,
                )

**Comment by jirikuncar** [comment]
> @lnielsen the code you mention is not extensible. Instead each service would need to reimplement it from scratch and they would probably need to add a signal or something similar in order be able to plug little by little more enhancers.

That's the point - different services have different needs - celery, enhancers, ... until there is more stable solution then `models_committed` we are not going to provide other signals.

> Addditionally the receiver in the mentioned code is triggered upon every model being touched. Isn't this overkill?

There is no better way so far. See SQLAlchemy bitbucket issue with the discussion ...

> A dedicated signal for indexing seems to me a more high-level and semantic approach.

You can define as many signals in your overlay as you want. However there are drawbacks you have to face yourself with ordering such signals. That's why we went to solution that was implemented.

**Comment by jirikuncar** [comment]
Following discussion should be made in *Invenio-Search* repository.
