### ISSUE TITLE
tests: best practice for tests involving records

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-records#49]
What is the recommended best practice to write unit/regression tests involving the creation of temporary records? In particular taking into consideration that the test might involve a celery task.

Is there a clean way to *entirely delete* a test record upon `tearDown()`?

**Comment by lnielsen** [comment]
I think here you think of integration testing on e.g. INSPIRE since the records module itself should not be running Celery tasks, it should just send out signals (which is much more easily tested).

Possible ways:
1) Use SQLite and simply create/drop the entire DB in memory for every test.
2) Mock the record (i.e. no data storage behind it).
3) Wrap tests in transactions, and rollback the transaction on teardown.

**Comment by jirikuncar** [comment]
FYI I was experiencing problems with SQLite and nested transactions, however postresql and mysql are fine.

**Comment by lnielsen** [comment]
In Invenio 3.0, each unit test can creates/drop the database (see e.g. PIDStore) - this way you have a clean DB. You can the create records using the programatic API.

```
recid=uuid.uuid4()
Record.create({'title': 'My Title'}, id=recid)
```

If you need to run Celery tasks, then you can run them eagerly in the tests. See example here in Invenio-Records.

@kaplun Can I close the issue?

**Comment by kaplun** [comment]
Setting up and tearing down the DB each time, isn't going to be OK for testing single modules, but what would you suggest for integration testing, i.e. for testing the overlay. There you might have hundredths of real life tests, and to each time setup a DB and reinitialize all fixtures is not feasible. In that case a clean pattern where you can do temporary modifications to the DB and roll them back is still needed. What do you plan to do for Zenodo?

**Comment by lnielsen** [comment]
I plan to use something a long the lines of http://alexmic.net/flask-sqlalchemy-pytest/ but haven't gotten so far yet. I.e. create test database, and wrap it in a transaction that can be rolled back.

**Comment by tiborsimko** [comment]
@kaplun Another thing is that hopefully a certain *family* of integration tests in the overlay can share the same fixtures, e.g. testing various search facilities on top of a populated database.  There should be no need to pre-load the database values anew for every individual test...

**Comment by lnielsen** [comment]
See example in https://github.com/inveniosoftware/invenio-records-rest/blob/master/tests/conftest.py#L179-L237

Integration testing can use: 
- pytest fixtures with **session** scope (so db/index creation persist over tests), and
- separate tests into non-destructive vs destructive tests (similar to how I've separate ``e2e`` and ``unit`` tests on Zenodo - i.e. you'll have two or more directories with their own ``conftest.py``)

Added benefit of above is that you can easily distribute your tests on Travis, and thereby cut down the time it takes for a full build.
