### ISSUE TITLE
RFC table name standardisation

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-records#63]
The Invenio-Records module tables bear a "traditional" name in singular, i.e. `record`. It may be good to profit from migration to Invenio v3.0 in order to standardise table names and module names globally.  E.g. the currently created Invenio v3.0 tables are:

```
invenio3=# \dt 
               List of relations
 Schema |       Name        | Type  |  Owner
--------+-------------------+-------+----------
 public | accounts_role     | table | invenio3
 public | accounts_user     | table | invenio3
 public | accounts_userrole | table | invenio3
 public | pidLOG            | table | invenio3
 public | pidSTORE          | table | invenio3
 public | record            | table | invenio3
 public | record_version    | table | invenio3
 public | transaction       | table | invenio3
(8 rows)
```

Note that pidSTORE and pidLOG is better to be expressed in all lowercase for easy PostgreSQL compliance. This seems to be already in the target of https://github.com/inveniosoftware/invenio-pidstore/pull/31

Note "accounts" but "record".

Note "accounts" but "user".

Proposed new convention: `tablename = modulename_*` which would call for using `records` and `editor` prefixes for tables, to take two examples.  This would align table naming convention to our [our module naming convention](http://pythonhosted.org/invenio/architecture/module-anatomy-naming.html).

CC @jirikuncar @lnielsen @nharraud

**Comment by jirikuncar** [comment]
WDYT about `records_metadata` & `records_metadata_version`?

**Comment by tiborsimko** [comment]
@jirikuncar Sounds nice! Perhaps `records_metadata_versions` to keep plural?  (and we can go for `accounts_users` etc)

**Comment by jirikuncar** [comment]
`*_version` is auto-generated by SQLAlchemy-Continuum.

**Comment by tiborsimko** [comment]
OK, I see.

**Comment by nharraud** [comment]
Maybe we could add in the documentation that every third party module, i.e from services like B2Share, should prefix the table names with the service name or an abbreviation (`b2s_*`). This would prevent future collisions on common names like community, user, etc... and make migrations easier if a service wants to replace their old modules with the ones provided by Invenio.

**Comment by kaplun** [comment]
> Maybe we could add in the documentation that every third party module, i.e from services like B2Share, should prefix the table names with the service name or an abbreviation (b2s_*).

:+1: sounds really a clean idea to support migrations (a bit like custom HTTP headers when they then become standards)

**Comment by lnielsen** [comment]
Note that table names in PIDStore have already been fixed in the rewrite.

**Comment by lnielsen** [comment]
Do we go with plural or singular in the ending?

**Comment by jirikuncar** [comment]
If we go with class name in singular form we should do the same with database name. Otherwise I would be a fan of following http://book.cakephp.org/3.0/en/intro/conventions.html#model-and-database-conventions

**Comment by lnielsen** [comment]
:+1: for singular form.
