### ISSUE TITLE
api: record validation tests

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records#66]
Ensure record validation works:

- [x] Integration with JSONResolver
  - [x] fast retrieval of local referenced schemas (#69)
  - [x] fast retrieval of links between records
- [x] Add test cases for schema validation. (#69)

**Comment by jirikuncar** [comment]
> - [ ] fast retrieval of links between records

This is possible to solve only on "overlay" level or with combination of advanced `invenio-records-ui` endpoint registration and moving to `someday`. /cc @lnielsen

**Comment by jirikuncar** [comment]
Last task solved in #91.
