### ISSUE TITLE
admin: add admin interface to records

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records#67]
Add a "low-level" admin interface (if Invenio-Admin is installed), that allows 

- [ ] inspecting the raw content of records as well as previous versions.
- [ ] revert a record to a previous version.

No search feature needed. 

(should this admin go in invenio-records or in invenio-records-ui?)

**Comment by jirikuncar** [comment]
- [ ] extra_requires['admin'] = [invenio-admin, invenio-access]

**Comment by jirikuncar** [comment]
Closed via #84
