### ISSUE TITLE
after_record_update and previous version

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-records#87]
In the receivers of `after_record_update` signal, in INSPIRE, we need to know what has changed in the record in order to propagate certain modifications (e.g. say a record initially refers to A, B, C records, and subsequently it is modified to refer instead to records B, C, and D: we need to programmatically reindex records A and D in order to recompute the number of citations).

For this reason in the unsupported Invenio 2.x we are patching invenio-records to take a snapshot of the original record before modification and send it as a second parameter when calling `after_record_update`.

In Invenio 3.x how this requirement will be supported? Is there a way for a receiver to retrieve easily the previous version of the record before the current update? I see there is a `revisions` property that can be queried, however this seems a bit heavier for the purpose (as one would need to iterate all the revisions in order to obtain the last-before-the-current-one).

cc: @tomaszgy

**Comment by jirikuncar** [comment]
The correct way is using `revisions` in asynchronous event handler (celery task).

**Comment by lnielsen** [comment]
The ``revisions`` property support indexing so you can do stuff like:

```python
record.revisions[-1] 
```

**Comment by lnielsen** [comment]
@kaplun You mentioned today IRL that you'll be able to use the revisions property so I'm closing this issue. In case I misunderstood, just re-open :-)

**Comment by kaplun** [comment]
Sure. This was indeed a `question` issue. :smile:

**Comment by kaplun** [comment]
Just one question on the performance though: the `revisions` property is infact a cursor. So going to the last element would still require to scroll the whole results, isn't it? Imagine the typical records of INSPIRE and CDS, 1MB of metadata for each revision, and ~20 revisions on average. In that case there would be 20MB travelling the wire just to retrieve the previous modifications in the current session.

**Comment by jirikuncar** [comment]
@kaplun if you find performance issues we can optimize it later.

**Comment by kaplun** [comment]
Sure. I am just raising an early warning since this performance issue will happen eventually, since the revisions are always growing. On INSPIRE we have certain records with up to 300 revisions (since every automatic barely touching a record is creating a revision).
